name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: mcr.microsoft.com/playwright:focal
        options: --privileged
        ports:
          - 9222:9222

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx cucumber-js

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean
          allure open
